<h5>Clients</h5>
<p>Clients can be created in two ways - either via the Sync with Campaign Monitor or by signing up through the website.  Clients can either be <code>Awaiting Approval</code>, <code>Active</code> or <code>Inactive</code>.</p>
<h5>Awaiting Approval</h5>
<p>When a client first signs up, they are <code>Awaiting Approval</code>.  At this point they have only been created in the Campaign Press database, and not in Campaign Monitor yet.  Clients awaiting approval can have their details updated (name, description, group etc.), be approved (at which point they will become <code>Active</code>) or be deleted entirely (completely removed from the system).</p>
<p>If a client awaiting approval is approved, they will be created within Campaign Monitor using the specified <code>Group</code> to dictate their access &amp; billing settings.  If the group allows them access to Campaign Monitor, a username (generated from their company name if none had been specified up to this point) and a random temporary password will be generated for them.  These can be sent out on the email notification that the client received on sign up.</p>
<h5>Active</h5>
<p>Once a client is in Campaign Monitor (through the approval process outlined above or through the Sync process) they are considered <code>Active</code>.  All details except for their username &amp; group can be updated through the Campaign Press interface (the reason the username &amp; group cannot be updated is because Campaign Monitor currently requires both the username &amp; password in order to change a client's access &amp; billing details - this is expected to be enabled soon) and the changes will be reflected inside Campaign Monitor.</p>
<p><code>Active</code> clients may not be deleted from within Campaign Press.  A client must first be deleted from within Campaign Monitor.  A Sync must then be performed (by clicking <i>Sync with Campaign Monitor</i> on the settings page) at which point all the clients deleted from Campaign Monitor will be made <code>Inactive</code>.</p>
<h5>Inactive</h5>
<p><code>Inactive</code> clients may be deleted from within Campaign Press.  Deleting a client will also remove all audit history for that client.</p>